### ISSUE TITLE
Complete data set

### ISSUE THREAD

**Issue by R09524081** [akashjn/FlavonoidsWithAL#1]
The complete data sets for the Redox potential and Solvation value are not provided. Only the training data set is provided.

**Comment by akashjn** [comment]
Thanks for pointing that out. 

I have added a Data.zip file to this repo which contains redox potentials and solvation energies of 10 initial training set molecules, and AL-selected 100 flavone and 50 isoflavone molecules.

**Comment by R09524081** [comment]
Hello,

It seems that the new Data.zip file still only contains Esol and Eoxi
values for ytrain.

Is it possible for you to provide the Esol and Eoxi values for all 60K
flavone dataset? Thank you!

akashjn ***@***.***> 於 2024年5月6日 週一 上午10:21寫道：

**Comment by akashjn** [comment]
No. I didn't calculate Esol and Eoxi for all 60K flavone.
